### ISSUE TITLE
Script grad_fit_h1_shape.py Missing

### ISSUE THREAD

**Issue by Mrsirovo** [LeCAR-Lab/human2humanoid#1]
Thank you for sharing the great work!
In motion retargeting, I discovered one missing script: human2humanoid/scripts/data_process/grad_fit_h1_shape.py.

**Comment by TairanHe** [comment]
Thank you for letting us know. We will add this file ASAP

**Comment by ZhengyiLuo** [comment]
Released!

**Comment by lzpyx** [comment]
> Released!
Thank you for your excellent work! I ran into a few problems running grad_fit_h1_shape.py, the first was that there were still parts of the code that imported uhc, so I brought uhc into the codebase and installed mujoco. After that, I encountered another problem:
```
Exception has occurred: ValueError
'left_ankle_link' is not in list
  File "/home/human2humanoid/scripts/data_process/grad_fit_h1_shape.py", line 68, in <listcomp>
    h1_joint_pick_idx = [ h1_joint_names_augment.index(j) for j in h1_joint_pick]
  File "/home/human2humanoid/scripts/data_process/grad_fit_h1_shape.py", line 68, in <module>
    h1_joint_pick_idx = [ h1_joint_names_augment.index(j) for j in h1_joint_pick]
ValueError: 'left_ankle_link' is not in list
```

**Comment by lzpyx** [comment]
> > Released!
> 
> Thank you for your excellent work! I ran into a few problems running grad_fit_h1_shape.py, the first was that there were still parts of the code that imported uhc, so I brought uhc into the codebase and installed mujoco. After that, I encountered another problem:
> 
> ```
> Exception has occurred: ValueError
> 'left_ankle_link' is not in list
>   File "/home/human2humanoid/scripts/data_process/grad_fit_h1_shape.py", line 68, in <listcomp>
>     h1_joint_pick_idx = [ h1_joint_names_augment.index(j) for j in h1_joint_pick]
>   File "/home/human2humanoid/scripts/data_process/grad_fit_h1_shape.py", line 68, in <module>
>     h1_joint_pick_idx = [ h1_joint_names_augment.index(j) for j in h1_joint_pick]
> ValueError: 'left_ankle_link' is not in list
> ```


There were some minor issues with grad_fit_h1_shape.py and grad_fit_h1.py, which I was able to run successfully by modifying the following sections:
For grad_fit_h1_shape.py
1. change h1_joint_names from h1-2 to h1 
2. dof_pos = torch.zeros((1, 19))
3. joblib.dump(shape_new.detach(), “data/h1/shape_optimized_v1.pkl”) 
For grad_fit_h1.py
1. copy amass_copycat_take6_train.pkl from phc repository
2. Comment out the following code in the fk_batch function         
# wbody_pos = wbody_pos[... , :-self._remove_idx, :]
# wbody_mat = wbody_mat[... , :-self._remove_idx, :, :]
# wbody_rot = wbody_rot[... , :-self._remove_idx, :]
3. replace joblib.load(“data/h1/amass_test.pkl”) with save code
Please let me know if I've made any inappropriate changes, thanks!

**Comment by TongZhangTHU** [comment]
@lzpyx Your modification was really helpful! Could you let me know where we can find the file amass_copycat_take6_train.pkl? I wasn't able to locate it in the PHC repository.

**Comment by lzpyx** [comment]
> @lzpyx Your modification was really helpful! Could you let me know where we can find the file amass_copycat_take6_train.pkl? I wasn't able to locate it in the PHC repository.

You should follow the "Data Processing AMASS" in PHC. After that, you could find the file in sample_data/amass_copycat_take6_train.pkl

**Comment by TongZhangTHU** [comment]
@lzpyx Thanks so much for your help! It works perfectly. By the way, it seems that running grad_fit_h1.py takes over 25 hours. Is that normal?

**Comment by lzpyx** [comment]
I think so. It's gonna take quite a while.

> @lzpyx Thanks so much for your help! It works perfectly. By the way, it seems that running grad_fit_h1.py takes over 25 hours. Is that normal?

**Comment by TongZhangTHU** [comment]
@lzpyx Thank you!  If that's the case, how can we achieve retargeting during real-time teleoperation? Retargeting requires 500 iterations, which makes it run very slowly.

**Comment by HaodongHuang-W** [comment]
@Mrsirovo Thank you very much for your correction. I fixed the three errors in grad_fit_h1_shape.py you mentioned, and then ran `python scripts/data_process/grad_fit_h1_shape.py,` and the following problem occurred
`> /media/ubuntu/39AD5F31453C9CE4/human2humanoid/isaacgym/python/examples/human2humanoid/scripts/data_process/grad_fit_h1_shape.py(113)<module>()
111 optimizer_shape.step()
112 import ipdb; ipdb.set_trace()
--> 113 joblib.dump(shape_new.detach(), "data/h1/shape_optimized_v1.pkl") # V2 has hip jointsrea

ipdb>`
Stuck here.

**Comment by YechenZhou** [comment]
> 1. amass_copycat_take6_train.pkl

fail to get amass_copycat_take6_train.pk, could you provide it for me？ Thanks.
