### ISSUE TITLE
Different tasks for display

### ISSUE THREAD

**Issue by xuai05** [LeCAR-Lab/human2humanoid#12]
How can I set different tasks for display when running play_hydra.py?

**Comment by xuai05** [comment]
Such as playing OmniH2O_TEACHER：The visualization shows a person standing with his back to the screen performing a side-to-side swaying motion.
`python  legged_gym/scripts/play_hydra.py --config-name=config_teleop task=h1:teleop env.num_observations=913 env.num_privileged_obs=990 motion.future_tracks=True motion.teleop_obs_version=v-teleop-extend-max-full motion=motion_full  motion.extend_head=True asset.zero_out_far=False asset.termination_scales.max_ref_motion_distance=10.0  sim_device=cuda:0 load_run=OmniH2O_TEACHER checkpoint=XXXX num_envs=1 headless=False`
![1729499978239](https://github.com/user-attachments/assets/62873785-14b4-4070-ad9f-68fd38fb000a)

Such as playing OmniH2O_STUDENT：The visualization shows a person standing sideways facing the screen and swinging his hand.
`python legged_gym/scripts/play_hydra.py --config-name=config_teleop task=h1:teleop env.num_observations=1665 env.num_privileged_obs=1742 motion.teleop_obs_version=v-teleop-extend-vr-max-nolinvel motion.teleop_selected_keypoints_names=[] motion.extend_head=True num_envs=1 asset.zero_out_far=False asset.termination_scales.max_ref_motion_distance=10.0 sim_device=cuda:0 load_run=OmniH2O_STUDENT checkpoint=XXXX env.add_short_history=True env.short_history_length=25 headless=False`
![1729499836319](https://github.com/user-attachments/assets/f9b8229f-cab5-4036-8ffd-29e6fb64848a)

**Comment by TairanHe** [comment]
keyboard press T then you get to the next motion
