### ISSUE TITLE
关于状态空间的版本和实机部署

### ISSUE THREAD

**Issue by Leeeeeeeeeeeeeeeeeeeeeeeeeeeeeo** [LeCAR-Lab/human2humanoid#14]
大佬你好，请问这么多版本的obs各自的作用是什么？
![image](https://github.com/user-attachments/assets/92a9fbbe-80da-43e8-8d44-31a827eaf73f)

我已经使用了经过过滤后的数据集训练的privileged teacher policy，接下来如果要实机部署的话是使用以下参数吗
`--config-name=config_teleop task=h1:teleop run_name=OmniH2O_STUDENT env.num_observations=1665 env.num_privileged_obs=1742 motion.teleop_obs_version=v-teleop-extend-vr-max-nolinvel motion.teleop_selected_keypoints_names=[] motion.extend_head=True num_envs=4096 asset.zero_out_far=False asset.termination_scales.max_ref_motion_distance=1.5 sim_device=cuda:0 motion.motion_file=resources/motions/h1/stable_punch.pkl rewards=rewards_teleop_omnih2o_teacher rewards.penalty_curriculum=True rewards.penalty_scale=0.5 train.distill=True train.policy.init_noise_std=0.001 env.add_short_history=True env.short_history_length=25 noise.add_noise=False noise.noise_level=0 train.dagger.load_run_dagger=TEACHER_RUN_NAME train.dagger.checkpoint_dagger=XXX train.dagger.dagger_only=True`

我看到最下面的 H2O Policy (8point tracking, no history, MLP, with linear velocity in the state space)是没有线速度的，而且没有对髋关节进行跟踪，这个Policy能否部署到实机上呢？

**Comment by TairanHe** [comment]
Hi你好，obs版本多的原因是因为我开发过程中迭代了非常多的状态空间选择。H2O policy是可以部署到实机的。感谢！

**Comment by Leeeeeeeeeeeeeeeeeeeeeeeeeeeeeo** [comment]
感谢大佬回复！
另外我想请教一下：
(1)项目中提到的使用HybrIK进行人体位姿估计，得到的SMPL格式的24*3维关键点位置是可以作为H2O Policy的输入的吗？
(2)如何修改HybrIK使其可以实时估计人体位姿，并且达到30Hz，我目前使用4080s显卡，处理速度是3.42it/s

**Comment by TairanHe** [comment]
1. H2O是8点（肩、肘、手，脚踝）输入，你可以选择SMPL的关键点（肩、肘、手，脚踝）喂给H2O
2. 我当时实验是4090，可以跑到30hz

**Comment by chenyunzhanggit** [comment]
> 感谢大佬回复！ 另外我想请教一下： (1)项目中提到的使用HybrIK进行人体位姿估计，得到的SMPL格式的24*3维关键点位置是可以作为H2O Policy的输入的吗？ (2)如何修改HybrIK使其可以实时估计人体位姿，并且达到30Hz，我目前使用4080s显卡，处理速度是3.42it/s

请问兄弟，hybrik 处理之后的数据中，代表 translation 的是不是 "transl", 代表关节转角的是不是 "pred_thetas"，但其数据描述是旋转矩阵，需要转换为 轴角表示？他的数据顺序会有什么改变吗？ 还是都是标准的  smpl 格式下关键点的数据顺序？ 

求教！目前卡在这一步，感谢！

**Comment by ZhangZoffy** [comment]
我也卡在这儿了，从hybrik获取了输出的数据后能不能直接用scripts/data_process/grad_fit_h1.py的方法进行适配，再用scripts/vis/vis_motion.py进行显示？目前这么操作后显示的人是躺着的。你解决了吗？@chenyunzhanggit

**Comment by Leonard-Tang** [comment]
需要改一下四元数的顺序，isaacgym里的是wxyz好像



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年7月31日(周四) 下午5:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LeCAR-Lab/human2humanoid] 关于状态空间的版本和实机部署 (Issue #14)


ZhangZoffy left a comment (LeCAR-Lab/human2humanoid#14)
 
***@***.***

**Comment by Hahalim2022y** [comment]
> > 感谢大佬回复！ 另外我想请教一下： (1)项目中提到的使用HybrIK进行人体位姿估计，得到的SMPL格式的24*3维关键点位置是可以作为H2O Policy的输入的吗？ (2)如何修改HybrIK使其可以实时估计人体位姿，并且达到30Hz，我目前使用4080s显卡，处理速度是3.42it/s
> 
> 请问兄弟，hybrik 处理之后的数据中，代表 translation 的是不是 "transl", 代表关节转角的是不是 "pred_thetas"，但其数据描述是旋转矩阵，需要转换为 轴角表示？他的数据顺序会有什么改变吗？ 还是都是标准的 smpl 格式下关键点的数据顺序？
> 
> 求教！目前卡在这一步，感谢！

你好！我也卡在这一步，请问hybrik的输出怎么给h2o的运动重定向？我使用了一帧的transl(1，3)和pred_thetas(1，24*3*3)，重定向结果并不理想，您可以给我一些建议吗？非常感谢！
