### ISSUE TITLE
Question about the Gait

### ISSUE THREAD

**Issue by zengweishuai** [LeCAR-Lab/human2humanoid#17]
Hi, thanks for your great work again!

After training the privileged policy and the distilled policy, I notice that the gait of the humanoid robot seems a little weird. To be specific, when it tries to walk forward, there is only one leg trying to follow the reference motion while the other falls behind as if the robot were lamp. 

The checkpoint I use is 25000 for privileged policy and 18000 for distilled policy. 

Can you share some clues why this may happen? I am sorry for my disturbance. Expect your reply!

**Comment by zengweishuai** [comment]
Hi @TairanHe, thanks for your reply!

There is a gif describing the situation I've encountered when selecting the 26500 checkpoints for the privileged policy:

![priv_3](https://github.com/user-attachments/assets/54de1a78-0f17-46c0-b2a2-56245d0e6660)

The reason why I choose such checkpoint is that I notice in the reward result graph, the reward would decline after about 1.5M steps. So I choose a checkpoint between 1M steps and 1.5M steps (between checkpoint 25000 and 35000). Is the training graph correct? The graph is attached below:

![result](https://github.com/user-attachments/assets/8a517bf1-be9e-42d1-907c-200e04c2af51)

The default reward you've mentioned refers to using the rewards_base.yaml to train? 

Thanks again for your quick reply!

**Comment by TairanHe** [comment]
Hi, there is a penalty curriculum setting in omnih2o, which means the coef for negative reward will automatically increase/decrease based on the policy episode length. So the policy you chose may not fully converge. You can plot the penalty_coef in you wandb for details

**Comment by zengweishuai** [comment]
Hi, thanks for your reply! Problem has been solved!

**Comment by baolef** [comment]
> Hi [@TairanHe](https://github.com/TairanHe), thanks for your reply!
> 
> There is a gif describing the situation I've encountered when selecting the 26500 checkpoints for the privileged policy:
> 
> ![priv_3](https://github.com/user-attachments/assets/54de1a78-0f17-46c0-b2a2-56245d0e6660) [ ![priv_3](https://github.com/user-attachments/assets/54de1a78-0f17-46c0-b2a2-56245d0e6660) ](https://private-user-images.githubusercontent.com/169873775/382997629-54de1a78-0f17-46c0-b2a2-56245d0e6660.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk3MjAwNjYsIm5iZiI6MTc0OTcxOTc2NiwicGF0aCI6Ii8xNjk4NzM3NzUvMzgyOTk3NjI5LTU0ZGUxYTc4LTBmMTctNDZjMC1iMmEyLTU2MjQ1ZDBlNjY2MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxMlQwOTE2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTNiMzE4ZmFkN2RjMDlkYjM3ZjZjMmExYmRlMDYzZDBiZGFjZmFjMzYxN2MxYzljMTgxYTAwMWU5MDMzOWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BitzKaMBhD-LPmN3EOE5kbocaAKXkgmS6NzljVfDmck) [ ](https://private-user-images.githubusercontent.com/169873775/382997629-54de1a78-0f17-46c0-b2a2-56245d0e6660.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDk3MjAwNjYsIm5iZiI6MTc0OTcxOTc2NiwicGF0aCI6Ii8xNjk4NzM3NzUvMzgyOTk3NjI5LTU0ZGUxYTc4LTBmMTctNDZjMC1iMmEyLTU2MjQ1ZDBlNjY2MC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYxMlQwOTE2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTNiMzE4ZmFkN2RjMDlkYjM3ZjZjMmExYmRlMDYzZDBiZGFjZmFjMzYxN2MxYzljMTgxYTAwMWU5MDMzOWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BitzKaMBhD-LPmN3EOE5kbocaAKXkgmS6NzljVfDmck)
> 
> The reason why I choose such checkpoint is that I notice in the reward result graph, the reward would decline after about 1.5M steps. So I choose a checkpoint between 1M steps and 1.5M steps (between checkpoint 25000 and 35000). Is the training graph correct? The graph is attached below:
> 
> ![result](https://github.com/user-attachments/assets/8a517bf1-be9e-42d1-907c-200e04c2af51)
> 
> The default reward you've mentioned refers to using the rewards_base.yaml to train?
> 
> Thanks again for your quick reply!

Do you know if there is an elegant way to visualize this motion apart from hardcoding it in the [_load_motion](https://github.com/LeCAR-Lab/human2humanoid/blob/fb7ed5f85c4426f7c52cc3f82e43ee4de215bee9/legged_gym/legged_gym/envs/base/legged_robot.py#L3123) or [get_motion_state](https://github.com/LeCAR-Lab/human2humanoid/blob/28b5986fd6854cae8597cd96a6dd123dd97e3b00/phc/phc/utils/motion_lib_h1.py#L353)? For example, can we switch the camera when loading multiple motions in [play_hydra.py](https://github.com/LeCAR-Lab/human2humanoid/blob/43665822657d8c856658add6ae1db4e8521d1f1b/legged_gym/legged_gym/scripts/play_hydra.py)?

Besides, is the locomotion problem solved just by training for more iterations?

Thank you!
