### ISSUE TITLE
Run 'render_smpl_o3d.py' fail to find file 'output/renderings/smpl_im_comp_8-2023-02-05-15:36:14.pkl'

### ISSUE THREAD

**Issue by YechenZhou** [LeCAR-Lab/human2humanoid#19]
Hi, thanks for releasing the code. I run 'render_smpl_o3d.py' fail to find file 'output/renderings/smpl_im_comp_8-2023-02-05-15:36:14.pkl'. Where can I find this file? Also, is there any visual auxiliary python script to help me verify the effect of the SMPL body model fitting to my custom humanoid robot?

**Comment by ZhengyiLuo** [comment]
Please run `vis_motion.py` to visualize the related motion.
