### ISSUE TITLE
Teleoperaion of H1 with Vision pro or rgb camera

### ISSUE THREAD

**Issue by bethalageetachandraraju** [LeCAR-Lab/human2humanoid#2]
OpenTelevision is focused on H1_2 robot, where the dds communication protocol is different, how were you able to change t for H1 robot. could you release the code for teleoperation of H1 with vision pro.

**Comment by TairanHe** [comment]
Hi,

Regardless of the teleoperation interface in use, the key requirement is the desired humanoid pose for tracking. Our system broadcasts the hand-head pose from the Vision Pro to the OmniH2O/H2O policy via ROS1, making the integration process straightforward and independent of the specific robot.

Best regards,
Tairan

**Comment by bethalageetachandraraju** [comment]
Thanks for the reply,
one question, how you were controlling the H1 wrist, and is your whole code base is in onboard NVIDIA computer?
arent you controlling from external PC?
and for the ros part, did you installed the ros separately or using the pre installed ros2?

**Comment by bethalageetachandraraju** [comment]
can you guide us how to run from external PC like and example code and terminal cmds.

**Comment by TairanHe** [comment]
https://support.unitree.com/home/en/H1_developer
