### ISSUE TITLE
Question about the result of the Motion Retargeting

### ISSUE THREAD

**Issue by jaggerShen** [LeCAR-Lab/human2humanoid#20]
I have done the retargeting loop, and get the output file 'amass_test.pkl'. I have question about it.
(1) How to use the output file? Is the 'amass_test.pkl' same as the 'amass_phc_filtered.pkl' which is download from the [link](https://cmu.app.box.com/s/vfi619ox7lwf2hzzi710p3g2l59aeczv) ? Shoule I have to train a privileged teacher policy without any domain randomization or penalty reward. Then use the privileged teacher policy to filter and obtain a new file 'amass_phc_filtered.pkl' ? Or I can directly use the link file.

**Comment by jaggerShen** [comment]
> I have done the retargeting loop, and get the output file 'amass_test.pkl'. I have question about it. (1) How to use the output file? Is the 'amass_test.pkl' same as the 'amass_phc_filtered.pkl' which is download from the [link](https://cmu.app.box.com/s/vfi619ox7lwf2hzzi710p3g2l59aeczv) ? Shoule I have to train a privileged teacher policy without any domain randomization or penalty reward. Then use the privileged teacher policy to filter and obtain a new file 'amass_phc_filtered.pkl' ? Or I can directly use the link file.

by the way, I using another humanoid

**Comment by AKshang** [comment]
I have the same question, are these two files the same?

**Comment by AKshang** [comment]
> > 我已经完成了重定向循环，并获得了输出文件 'amass_test.pkl'。我对此有疑问。（1） 如何使用输出文件？“amass_test.pkl”与从[链接](https://cmu.app.box.com/s/vfi619ox7lwf2hzzi710p3g2l59aeczv)下载的“amass_phc_filtered.pkl”是否相同？我应该训练一个特权教师政策，没有任何领域随机化或惩罚奖励。然后使用特权教师策略筛选并获取新文件 'amass_phc_filtered.pkl' ？或者我可以直接使用链接文件。
> 
> 顺便说一句，我用的是另一个人形机器人

I have the same question, are these two files the same?

**Comment by jaggerShen** [comment]
> > > 我已经完成了重定向循环，并获得了输出文件 'amass_test.pkl'。我对此有疑问。（1） 如何使用输出文件？“amass_test.pkl”与从[链接](https://cmu.app.box.com/s/vfi619ox7lwf2hzzi710p3g2l59aeczv)下载的“amass_phc_filtered.pkl”是否相同？我应该训练一个特权教师政策，没有任何领域随机化或惩罚奖励。然后使用特权教师策略筛选并获取新文件 'amass_phc_filtered.pkl' ？或者我可以直接使用链接文件。
> > 
> > 
> > 顺便说一句，我用的是另一个人形机器人
> 
> I have the same question, are these two files the same?

No, I think the file  'amass_phc_filtered.pkl'  is  obtained after the file  'amass_test.pkl' is cleaned. So if you have another robot, you must to make it feasible using data clean(privilege policy).

**Comment by AKshang** [comment]
> > > > 我已经完成了重定向循环，并获得了输出文件 'amass_test.pkl'。我对此有疑问。（1） 如何使用输出文件？“amass_test.pkl”与从[链接](https://cmu.app.box.com/s/vfi619ox7lwf2hzzi710p3g2l59aeczv)下载的“amass_phc_filtered.pkl”是否相同？我应该训练一个特权教师政策，没有任何领域随机化或惩罚奖励。然后使用特权教师策略筛选并获取新文件 'amass_phc_filtered.pkl' ？或者我可以直接使用链接文件。
> > > 
> > > 
> > > 顺便说一句，我用的是另一个人形机器人
> > 
> > 
> > 我有同样的问题，这两个文件是一样的吗？
> 
> 否，我认为文件 'amass_phc_filtered.pkl' 是在清理文件 'amass_test.pkl' 后获得的。因此，如果您有另一个机器人，则必须使用 data clean（特权策略） 使其可行。

I am working on creating my own human action dataset and trying to redirect it to a robot. I want to replace the AMASS dataset and the robot, but I am encountering an issue where the joint correspondences in pose_aa fail, and the redirection results are not as expected，Do you know about this issue?

**Comment by jaggerShen** [comment]
> > > > > 我已经完成了重定向循环，并获得了输出文件 'amass_test.pkl'。我对此有疑问。（1） 如何使用输出文件？“amass_test.pkl”与从[链接](https://cmu.app.box.com/s/vfi619ox7lwf2hzzi710p3g2l59aeczv)下载的“amass_phc_filtered.pkl”是否相同？我应该训练一个特权教师政策，没有任何领域随机化或惩罚奖励。然后使用特权教师策略筛选并获取新文件 'amass_phc_filtered.pkl' ？或者我可以直接使用链接文件。
> > > > 
> > > > 
> > > > 顺便说一句，我用的是另一个人形机器人
> > > 
> > > 
> > > 我有同样的问题，这两个文件是一样的吗？
> > 
> > 
> > 否，我认为文件 'amass_phc_filtered.pkl' 是在清理文件 'amass_test.pkl' 后获得的。因此，如果您有另一个机器人，则必须使用 data clean（特权策略） 使其可行。
> 
> I am working on creating my own human action dataset and trying to redirect it to a robot. I want to replace the AMASS dataset and the robot, but I am encountering an issue where the joint correspondences in pose_aa fail, and the redirection results are not as expected，Do you know about this issue?

1. I think it should be SMPL file for your dataset; 2. you shoulde use 'convert_amass_data.py' in [PHC repo](https://github.com/ZhengyiLuo/PHC/tree/master/scripts/data_process) to convert your dataset, then use it for 'grad_fit_h1.py'

**Comment by sunmengmm** [comment]
@jaggerShen Hello, I'm also using the retarget method provided by omnih2o applied to my own robot (not h1), have you encountered the foot overlapping/together? The same motion can be done on h1 with the feet standing naturally apart.
Here are my screenshots. Thank you very much if you can offer some advice.

![Image](https://github.com/user-attachments/assets/9ad0cfe8-ec79-4ca3-b0dc-92807fa57a6e)

![Image](https://github.com/user-attachments/assets/21ad01f0-403e-44d7-9799-fc99ed4169c0)

**Comment by ShealyXie** [comment]
> [@jaggerShen](https://github.com/jaggerShen) Hello, I'm also using the retarget method provided by omnih2o applied to my own robot (not h1), have you encountered the foot overlapping/together? The same motion can be done on h1 with the feet standing naturally apart. Here are my screenshots. Thank you very much if you can offer some advice.
> 
> ![Image](https://github.com/user-attachments/assets/9ad0cfe8-ec79-4ca3-b0dc-92807fa57a6e)
> 
> ![Image](https://github.com/user-attachments/assets/21ad01f0-403e-44d7-9799-fc99ed4169c0)

Same issue here! The feet of my own robot always overlaps a little bit even if I have set the L/R_Hip offset of the SMPL model. The grad_fit_shape_xx.py script works fine, but the grad_fit_xx.py (motion retargeting) cannot be improved. Have you solved problem? If so, could you please share the way of solving it?
