### ISSUE TITLE
I am using my own mp4 human action dataset to redirect it to a robot. The visualized results show correct actions, but the robot appears to be floating, with its feet not touching the ground. What could be the reason for this?

### ISSUE THREAD

**Issue by AKshang** [LeCAR-Lab/human2humanoid#24]
![屏幕截图 2024-12-02 212827](https://github.com/user-attachments/assets/e16e2088-0222-41d9-9e82-68cb7fa9a45d)
I am using my own mp4 human action dataset to redirect it to a robot. The visualized results show correct actions, but the robot appears to be floating, with its feet not touching the ground. What could be the reason for this?

**Comment by AKshang** [comment]
I suspect it might be an issue with the coordinate system definition, but I'm not sure how to modify it.

**Comment by TairanHe** [comment]
this might be due to wxyz and xyzw mismatch

**Comment by AKshang** [comment]
How should I modify it? Could you provide the modified code? My current approach is to multiply the redirected robot's pose_aa (22×3) by the rotation matrix, but it does not make the robot stand upright.

**Comment by ZhangZoffy** [comment]
I have the same problem. Do you solve it ?@AKshang
