### ISSUE TITLE
Discrepancy between IK and FK in retargeting human motion to humanoids

### ISSUE THREAD

**Issue by Maxwell-Zhao** [LeCAR-Lab/human2humanoid#25]
In the paper, the authors mention that they retarget human motions to the humanoid using inverse kinematics, but in the file grad_fit_h1_shape.py, it appears that forward kinematics is used instead of IK.

![QQ_1733317416654](https://github.com/user-attachments/assets/4727db7e-c640-4fc1-b290-4165f58b7ea1)

**Comment by Maxwell-Zhao** [comment]
This is a FK model in file grad_fit_h1_shape.py.
![QQ_1733317691605](https://github.com/user-attachments/assets/4838a758-92de-4bb6-8b38-48e3aa19de7e)

**Comment by TairanHe** [comment]
The IK is implemented based on optimization with FK.
