### ISSUE TITLE
How to Achieve Real-Time Teleoperation with SMPL2AMASS?

### ISSUE THREAD

**Issue by Maxwell-Zhao** [LeCAR-Lab/human2humanoid#26]
The paper describes using a network to predict SMPL parameters, which are then used to control the robot for teleoperation. However, in the code, the target motion for the robot is generated using the AMASS dataset format. To convert SMPL parameters into the AMASS format, it seems that the MoSh++ optimization process is required. How can real-time teleoperation be achieved under these constraints?

**Comment by Maxwell-Zhao** [comment]
I have another question. In the paper, the control is based on SMPL, but in the grad_fit_h1.py file, the AMASS data is further processed to match the H1 joint angles and degrees of freedom. How is this step achieved in real-time teleoperation? How is the conversion from SMPL to the output of file grad_fit_h1.py completed in real-time?

**Comment by Sureen99** [comment]
Hey did you manage to figure this out? I am stuck at this step too

**Comment by ZhangZoffy** [comment]
I am stuck at this step too。Did you salve the question？ @Maxwell-Zhao
