### ISSUE TITLE
How to achieve real-time teleoperation with human mocap result with fitting process

### ISSUE THREAD

**Issue by Maxwell-Zhao** [LeCAR-Lab/human2humanoid#28]
In the paper, it is claimed that real-time teleoperation can be achieved. However, for human motion data from the AMASS, it needs to be fitted to the robot before being used for training (in file grad_fit_h1.py). This raises a question: when using human mocap data for teleoperating the robot, does the process also require fitting? If fitting is indeed necessary, how to achieve real time teleoperation?

**Comment by TairanHe** [comment]
Hi, fitting is not necessary since we are tracking sparse keypoint positions (head and hands). We directly use the positions from MoCap/RGB/VR without any retargeting.
