### ISSUE TITLE
run grad_fit_h1_shape.py get "'left_ankle_link' is not in list" error

### ISSUE THREAD

**Issue by zhanggang11863976** [LeCAR-Lab/human2humanoid#3]
2024-10-04 17:43:57,027 - INFO - logger - logger initialized
Traceback (most recent call last):
  File "scripts/data_process/grad_fit_h1_shape.py", line 65, in <module>
    h1_joint_pick_idx = [ h1_joint_names_augment.index(j) for j in h1_joint_pick]
  File "scripts/data_process/grad_fit_h1_shape.py", line 65, in <listcomp>
    h1_joint_pick_idx = [ h1_joint_names_augment.index(j) for j in h1_joint_pick]
ValueError: 'left_ankle_link' is not in list

**Comment by wuhaichao87** [comment]
h1_joint_names = ['pelvis',
 'left_hip_yaw_link',
 'left_hip_pitch_link',
 'left_hip_roll_link',
 'left_knee_link',
 #'left_ankle_pitch_link',
 #'left_ankle_roll_link',
 'left_ankle_link',
 'right_hip_yaw_link',
 'right_hip_pitch_link',
 'right_hip_roll_link',
 'right_knee_link',
 #'right_ankle_pitch_link',
 #'right_ankle_roll_link',
 'right_ankle_link',
 'torso_link',
 'left_shoulder_pitch_link',
 'left_shoulder_roll_link',
 'left_shoulder_yaw_link',
 #'left_elbow_pitch_link',
 #'left_elbow_roll_link',
 'left_elbow_link',
# 'left_wrist_pitch_link',
# 'left_wrist_yaw_link',
 'right_shoulder_pitch_link',
 'right_shoulder_roll_link',
 'right_shoulder_yaw_link',
 #'right_elbow_pitch_link',
 #'right_elbow_roll_link',
 'right_elbow_link',
# 'right_wrist_pitch_link',
# 'right_wrist_yaw_link'
 ]

**Comment by TairanHe** [comment]
We’ll be updating the retargeting code with a cleaner, improved version soon. Please stay tuned, and in the meantime, use the provided retargeted .pkl file for temporary debugging with our code.

**Comment by HaodongHuang-W** [comment]
I encountered the same problem.

**Comment by IlanElfen** [comment]
Me too

**Comment by CavalloneChen** [comment]
I've encountered the same problem, please update the retargeting files.

**Comment by ZhengyiLuo** [comment]
We have patched the retargeting code in the newest commit. Thanks!
