### ISSUE TITLE
A question about retargeting please

### ISSUE THREAD

**Issue by smilefish110** [LeCAR-Lab/human2humanoid#30]
Hello,
  Thanks for your great work!
  I try to deploy the algorithm on another robot models and there is a problem with retargeting.
  Here is the action visualization after retargeting. It seems to be fine on H1, but the action is very poor on my own robot model. Are there any parameters in the retargeting code related to initialization? Which parameters need to be modified to solve the problem? I am a little confused. Could you please give me some ideas and suggestions?
  Best wishes!
![vokoscreen-2024-12-11_16-44-58](https://github.com/user-attachments/assets/cac00328-3984-4722-8eda-efd8dbd7a43a)
![vokoscreen-2024-12-11_16-46-11](https://github.com/user-attachments/assets/1276fe69-b8b0-4ad6-8964-b1c96fa6d318)

**Comment by smilefish110** [comment]
@ZhengyiLuo @TairanHe

**Comment by ZhengyiLuo** [comment]
Hi! During retargeting, only the keypoint position are optimized. To make make the feet to be more naturally, there probably needs to be a toe joint added. 


There is sim2sim code in this repo; human2humanoid/PHC is used as a library for some function access.

**Comment by smilefish110** [comment]
> Hi! During retargeting, only the keypoint position are optimized. To make make the feet to be more naturally, there probably needs to be a toe joint added.
> 
> There is sim2sim code in this repo; human2humanoid/PHC is used as a library for some function access.

Thank you for your reply!  I have solved this problem. But I still didn't find the deployment code in this repo. Could please offer that part? Thanks a lot.
