### ISSUE TITLE
grad_fit_h1_shape.py  dimension unmatch error 

### ISSUE THREAD

**Issue by zhanggang11863976** [LeCAR-Lab/human2humanoid#4]
pose_aa_h1 = torch.cat([torch.zeros((1, 1, 3)), H1_ROTATION_AXIS * dof_pos[..., None], torch.zeros((1, 2, 3))], axis = 1)
RuntimeError: The size of tensor a (19) must match the size of tensor b (27) at non-singleton dimension 1

**Comment by lzpyx** [comment]
I encountered the same issue, and I can get it to work after the following modifications [https://github.com/LeCAR-Lab/human2humanoid/issues/1#issuecomment-2393403844](url)

**Comment by zhanggang11863976** [comment]
thank you. I think it works.

**Comment by TairanHe** [comment]
We’ll be updating the retargeting code with a cleaner, improved version soon. Please stay tuned, and in the meantime, use the provided retargeted .pkl file for temporary debugging with our code.

**Comment by ZhengyiLuo** [comment]
We have patched the retargeting code in the newest commit. Thanks!
