### ISSUE TITLE
run "grad_fit_h1.py" failed with No such file or directory: 'amass_copycat_take6_train.pkl'

### ISSUE THREAD

**Issue by zhanggang11863976** [LeCAR-Lab/human2humanoid#5]
as title

**Comment by chenyunzhanggit** [comment]
I have met the same issue

**Comment by gautica** [comment]
Any solution about the missing "amass_copycat_take6_train.pkl"? Thank you very much

**Comment by TairanHe** [comment]
We’ll be updating the retargeting code with a cleaner, improved version soon. Please stay tuned, and in the meantime, use the provided retargeted .pkl file for temporary debugging with our code.

**Comment by chenyunzhanggit** [comment]
> Any solution about the missing "amass_copycat_take6_train.pkl"? Thank you very much

Sorry for the late reply. You can got to the repo: https://github.com/ZhengyiLuo/PHC and get the data after executing the 'download_data.sh'.

**Comment by chenyunzhanggit** [comment]
> @chenyunzhanggit I would like to ask whether I can directly run bash download_data.sh. I run the previous python scripts/vis/vis_motion_mj.py python scripts/joint_monkey_smpl.py and it keeps reporting an error.

Sorry, I don't get you. "download_data.sh" is just for downloading some data we need. Please give it a shot.

**Comment by YechenZhou** [comment]
Always get "To report issues, please visit https://github.com/wkentaro/gdown/issues.
Error:

	HTTPSConnectionPool(host='drive.google.com', port=443): Max retries
	exceeded with url: /uc?id=1fFauJE0W0nJfihUvjViq9OzmFfHo_rq0 (Caused by
	NewConnectionError('<urllib3.connection.HTTPSConnection object at
	0x74a1b114b670>: Failed to establish a new connection: [Errno 110]
	Connection timed out'))
"
Cannot get "amass_copycat_take6_train.pkl ", could you provide it and give a url link?

**Comment by ZhengyiLuo** [comment]
I have pushed a commit and hopefully fixed the issues.
