### ISSUE TITLE
Question Regarding Data Cleaning and Privileged Policy Training in H2O

### ISSUE THREAD

**Issue by Perkins729** [LeCAR-Lab/human2humanoid#6]
Thank you for your open-source work. I would like to attempt to replicate the data cleaning in H2O, specifically training the privileged policy in H2O and using the algorithm for data filtering. How can I achieve this?
1.Should I follow the instructions in the section “Try training and playing privileged teacher policy”? Are the privileged policies used for data cleaning in H2O the same as those in OmniH2O?
2.How is the filtering algorithm implemented?

**Comment by TairanHe** [comment]
Hi you should first finish the retargeting of the entire AMASS and train a privileged teacher policy without any domain randomization or penalty reward. Then use the privileged teacher policy to evaluate all the AMASS motions and filter out those motions where the privileged teacher policy fails to track (if at any timestep the reference motion distance > 0.5m)

**Comment by Perkins729** [comment]
Is the file amass_phc_filtered.pkl in [this link](https://cmu.box.com/s/vfi619ox7lwf2hzzi710p3g2l59aeczv) the result of the data processing steps you mentioned?

**Comment by TairanHe** [comment]
Yes!
