### ISSUE TITLE
apply for mdm data

### ISSUE THREAD

**Issue by Axian12138** [LeCAR-Lab/human2humanoid#7]
Hi, thanks for your great work!
in your paper, it shows Figure 4: OmniH2O policy tracks motion goals from a language-based human motion generative model. i wonder if you could share the human motion file (better if with retargeted motion data) generated by mdm?
Since i alse tried to track mdm-generated motion but found its somehow terrible (especially in real world). it'll help me a lot! thx

**Comment by TairanHe** [comment]
There is no motion data actually. We directly use the motion generated by MDM https://github.com/GuyTevet/motion-diffusion-model without any retargeting. Please let me know if you have more questions.
