### ISSUE TITLE
how to get root pos in real world

### ISSUE THREAD

**Issue by Axian12138** [LeCAR-Lab/human2humanoid#8]
Hi, i have a question about how to get p^real for student policy in real world.
![image](https://github.com/user-attachments/assets/a87eb8f7-06a2-471c-92c2-ce600f121869)
and i check your data. In  `compute_imitation_observations_teleop(root_pos, root_rot, root_vel, body_pos, ref_body_pos, time_steps)` , I think p^real means root_pos, root_rot, root_vel. 
so i wonder how to get p^real(root_pos, root_rot, root_vel.) in real world without MoCap? if you use imu to estimate it?

thanks!!

**Comment by TairanHe** [comment]
Hi, we use ZED mini's VIO module to estimate the real root pos. Check out the script at https://github.com/LeCAR-Lab/human2humanoid/blob/main/hardware_code/zed_odometry.py

**Comment by zengweishuai** [comment]
Hi @TairanHe @Axian12138 , sorry to interrupt! Which coordinate system are those three points obtained from VR device in? 

My understanding is that you've first aligned the coordinate system of VR device and ZED and then the positions you've obtained are relative to the world origin set up by ZED. 

Am I right? I'm not sure...

**Comment by TairanHe** [comment]
Yes, there is a offset between VR and ZED that needs to be aligned before real-time teleop
