### ISSUE TITLE
Questions about retargeting

### ISSUE THREAD

**Issue by zengweishuai** [LeCAR-Lab/human2humanoid#9]
Hi, thanks for releasing the code for retargeting!

There is a question expecting your reply:

- In grad_fit_h1.py where you do retargeting, there is a rotation which is sRot.from_quat([0.5, 0.5, 0.5, 0.5]).inv() applied to the root orientation extracted from the AMASS dataset. I wonder why we should do such inverse rotation though the results seem correct.

**Comment by Axian12138** [comment]
I think this is because the AMASS and Omniverse H2O simulation environments have different definitions for the rotation of the world coordinate system (the order of roll, pitch, and yaw).

**Comment by Axian12138** [comment]
I think this is because the AMASS and OmniH2O simulation environments have different definitions for the rotation of the world coordinate system (the order of roll, pitch, and yaw).

**Comment by zengweishuai** [comment]
> I think this is because the AMASS and OmniH2O simulation environments have different definitions for the rotation of the world coordinate system (the order of roll, pitch, and yaw).

Thanks for your answer!!
